// Copyright (c) Canaan Inc. All rights reserved.
// Licensed under the Apache license. See LICENSE file in the project root for full license information.

namespace Nncase.CodeGen.PyNTT;

public sealed record PyNTTBufferPointerTemplateModel(string Expression);

public sealed record PyNTTTensorLoadTemplateModel(
    string FunctionName,
    string SourceName,
    long SourceOffset,
    PyNTTBufferPointerTemplateModel Destination,
    string DType,
    string TritonDType,
    long[] LocalShape,
    long[] DestinationStrides,
    long[] GlobalShape,
    int? ShardAxis,
    string Comment);

public sealed record PyNTTTensorStoreTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Source,
    string DestinationName,
    long DestinationOffset,
    string DType,
    string TritonDType,
    long[] LocalShape,
    long[] SourceStrides,
    long[] GlobalShape,
    int? ShardAxis,
    string Comment);

public sealed record PyNTTElementwiseBinaryTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Lhs,
    PyNTTBufferPointerTemplateModel Rhs,
    PyNTTBufferPointerTemplateModel Output,
    string LhsDType,
    string RhsDType,
    string OutputDType,
    string LhsTritonDType,
    string RhsTritonDType,
    string OutputTritonDType,
    long[] LhsShape,
    long[] RhsShape,
    long[] OutputShape,
    long[] LhsStrides,
    long[] RhsStrides,
    long[] OutputStrides,
    long[] Shape,
    string BinaryExpression,
    string Op,
    string Comment);

public sealed record PyNTTElementwiseUnaryTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] OutputStrides,
    long[] Shape,
    string UnaryExpression,
    string Op,
    string Comment);

public sealed record PyNTTElementwiseCastTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] OutputStrides,
    long[] Shape,
    string CastExpression,
    string CastMode,
    string Comment);

public sealed record PyNTTElementwiseWhereTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Cond,
    PyNTTBufferPointerTemplateModel TrueValue,
    PyNTTBufferPointerTemplateModel FalseValue,
    PyNTTBufferPointerTemplateModel Output,
    string CondDType,
    string ValueDType,
    string OutputDType,
    string CondTritonDType,
    string ValueTritonDType,
    string OutputTritonDType,
    long[] CondShape,
    long[] TrueShape,
    long[] FalseShape,
    long[] OutputShape,
    long[] CondStrides,
    long[] TrueStrides,
    long[] FalseStrides,
    long[] OutputStrides,
    long[] Shape,
    string Comment);

public sealed record PyNTTConcatTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel[] Inputs,
    PyNTTBufferPointerTemplateModel Output,
    string OutputDType,
    string OutputTritonDType,
    long[][] InputShapes,
    long[][] InputStrides,
    long[] OutputShape,
    long[] OutputStrides,
    int Axis,
    string Comment);

public sealed record PyNTTGatherTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Index,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string IndexDType,
    string OutputDType,
    string InputTritonDType,
    string IndexTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] IndexShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] IndexStrides,
    long[] OutputStrides,
    int Axis,
    string Comment);

public sealed record PyNTTPadTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] OutputStrides,
    long[][] Pads,
    string PadValue,
    string Comment);

public sealed record PyNTTScatterNDTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Indices,
    PyNTTBufferPointerTemplateModel Updates,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string IndicesDType,
    string UpdatesDType,
    string OutputDType,
    string InputTritonDType,
    string IndicesTritonDType,
    string UpdatesTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] IndicesShape,
    long[] UpdatesShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] IndicesStrides,
    long[] UpdatesStrides,
    long[] OutputStrides,
    string Comment);

public sealed record PyNTTSliceTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] OutputStrides,
    long[] Starts,
    long[] Strides,
    string Comment);

public sealed record PyNTTConv2DTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Weights,
    PyNTTBufferPointerTemplateModel Bias,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string WeightsDType,
    string BiasDType,
    string OutputDType,
    string InputTritonDType,
    string WeightsTritonDType,
    string BiasTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] WeightsShape,
    long[] BiasShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] WeightsStrides,
    long[] BiasStrides,
    long[] OutputStrides,
    long[] Stride,
    long[] Padding,
    long[] Dilation,
    long Groups,
    string Comment);

public sealed record PyNTTTransposeTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] OutputStrides,
    int[] Perm,
    string Comment);

public sealed record PyNTTMatmulTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Lhs,
    PyNTTBufferPointerTemplateModel Rhs,
    PyNTTBufferPointerTemplateModel Output,
    string LhsDType,
    string RhsDType,
    string OutputDType,
    string LhsTritonDType,
    string RhsTritonDType,
    string OutputTritonDType,
    long[] LhsShape,
    long[] RhsShape,
    long[] OutputShape,
    long[] LhsStrides,
    long[] RhsStrides,
    long[] OutputStrides,
    bool TransposeA,
    bool TransposeB,
    string Scale,
    string Comment);

public sealed record PyNTTReduceTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] InputShape,
    long[] OutputShape,
    long[] InputStrides,
    long[] OutputStrides,
    int[] Axes,
    bool KeepDims,
    string ReduceOp,
    string InitValue,
    string UpdateExpression,
    string FinalizeExpression,
    string Comment);

public sealed record PyNTTSoftmaxTemplateModel(
    string FunctionName,
    PyNTTBufferPointerTemplateModel Input,
    PyNTTBufferPointerTemplateModel Output,
    string InputDType,
    string OutputDType,
    string InputTritonDType,
    string OutputTritonDType,
    long[] Shape,
    long[] InputStrides,
    long[] OutputStrides,
    int Axis,
    string Comment);
