name: compiler-build

on: [push, pull_request]

concurrency:
  group: compiler-build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/release/') }}

env:
  NUGET_CERT_REVOCATION_MODE: offline
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-native:
    name: build-native-${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - {name: aarch64-macos, os: macos-14, cmakeArgs: '', buildType: Release}
          - {name: x86_64-linux, os: ubuntu-latest, cmakeArgs: '', buildType: Release}
          - {name: x86_64-windows, os: windows-latest, arch: x64, cmakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl, buildType: Release}

    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up build environment (Windows, Visual Studio)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.config.arch}}
        if: runner.os == 'Windows'

      - name: Install Conan
        shell: bash
        run: |
          pip install conan==1.64
          conan remote add -i 0 sunnycase https://conan.sunnycase.moe

      - name: Configure Conan (Linux)
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
        if: runner.os == 'Linux'

      - name: Configure Conan (Macos)
        run: |
          conan config init
          sed -i '' 's/xtensalx7]/xtensalx7, arm64]/g' ~/.conan/settings.yml
          sed -i '' 's/"14.0"]/"14.0", "15"]/g' ~/.conan/settings.yml
        if: runner.os == 'Macos'

      - name: Configure CMake
        shell: bash
        run: |
          conan install . -if build --build=missing -s build_type=${{matrix.config.buildType}} --profile=default -o runtime=False -o python=True -o tests=True -s compiler.cppstd=20

      - name: Upload Conan Recipes
        env:
          CONAN_PASSWORD: ${{secrets.CONAN_SUNNYCASE_PASSWORD}}
        shell: bash
        run: |
          conan user sunnycase -r sunnycase -p $CONAN_PASSWORD
          conan upload "*" --all -r sunnycase -c

  build-manylinux-native:
    name: build-manylinux-native-${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - {name: x86_64-linux, os: ubuntu-latest, cmakeArgs: '', buildType: Release}

    steps:
      - uses: actions/checkout@v3

      - name: Build in docker (Linux)
        uses: docker://sunnycase/manylinux2014_x86_64
        with:
            args: /bin/bash tools/build.sh ${{secrets.CONAN_SUNNYCASE_PASSWORD}}
        if: runner.os == 'Linux'
