name: compiler-build

on: [push, pull_request]

concurrency:
  group: compiler-build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/release/') }}

env:
  NUGET_CERT_REVOCATION_MODE: offline
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-native:
    name: build-native-${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - {name: aarch64-macos, os: macos-14, buildType: Release}
          - {name: x86_64-windows, os: windows-latest, arch: x64, buildType: Release}

    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up build environment (Windows, Visual Studio)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.config.arch}}
        if: runner.os == 'Windows'

      - name: Install Conan
        shell: bash
        run: |
          pip install conan==2.6.0
          conan remote add sunnycase https://conan.sunnycase.moe --index 0

      - name: Configure
        shell: bash
        run: |
          conan install . --build=missing -s build_type=${{matrix.config.buildType}} -pr:a=toolchains/${{matrix.config.name}}.profile.jinja -o "&:runtime=False" -o "&:python=True" -o "&:tests=True"

      - name: Upload Conan Recipes
        env:
          CONAN_PASSWORD: ${{secrets.CONAN_SUNNYCASE_PASSWORD}}
        shell: bash
        run: |
          conan remote login -p $CONAN_PASSWORD sunnycase sunnycase
          conan upload "*" -r sunnycase -c

  build-manylinux-native:
    name: build-manylinux-native-${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - {name: x86_64-linux, os: ubuntu-latest, cmakeArgs: '', buildType: Release}

    steps:
      - uses: actions/checkout@v3

      - name: Build in docker (Linux)
        uses: docker://sunnycase/manylinux_2_28_x86_64:1.0
        with:
            args: /bin/bash tools/build.sh ${{secrets.CONAN_SUNNYCASE_PASSWORD}}
        if: runner.os == 'Linux'
